<div class="alert alert-block alert-info">
<center>ESTATÍSTICA APLICADA</center>
<center>PROJETO 1</center>
<center>ALUNO: Luís Felipe Ferreira Tavares Nonato</center>
</div>

<div class="alert alert-block alert-info">
    1° Tarefa
<div>

Sim, é possivel trazer os dados diretamente do site, mas para isso precisaremos importar a lib zipfile, já que os dados disponibilizados pela PRF foram liberados de forma comprimida (.zip)

In [1]:
#Importando bibliotecas necessarias
import zipfile as zf
import pandas as pd
import numpy as np

#importando dataframes do site da prf e guardando
df_2018 = pd.read_csv('https://arquivos.prf.gov.br/arquivos/index.php/s/MaC6cieXSFACNWT/download',encoding = 'latin1',compression = 'zip',sep=';')
df_2019 = pd.read_csv('https://arquivos.prf.gov.br/arquivos/index.php/s/kRBUylqz6DyQznN/download',encoding = 'latin1',compression = 'zip',sep=';')
df_2020 = pd.read_csv('https://arquivos.prf.gov.br/arquivos/index.php/s/jdDLrQIf33xXSCe/download',encoding = 'latin1',compression = 'zip',sep=';')
df_2021 = pd.read_csv('https://arquivos.prf.gov.br/arquivos/index.php/s/n1T3lymvIdDOzzb/download',encoding = 'latin1',compression = 'zip',sep=';')

In [2]:
#vizualizando primeiro dataframe
df_2018

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,99973.0,2018-01-01,segunda-feira,00:20:00,RJ,116.0,"303,5",RESENDE,Condutor Dormindo,Saída de leito carroçável,...,4,1,0,4,1,"-22,46937","-44,44705",SR-RJ,DEL5/7,UOP03/RJ
1,99976.0,2018-01-01,segunda-feira,00:40:00,SC,282.0,"0,4",FLORIANOPOLIS,Não guardar distância de segurança,Colisão traseira,...,2,1,0,2,2,"-27,59971687","-48,57565694",SR-SC,DEL8/1,UOP01/SC
2,99977.0,2018-01-01,segunda-feira,00:30:00,RJ,493.0,1,ITABORAI,Ultrapassagem Indevida,Colisão frontal,...,0,3,1,1,3,"-22,763901","-42,927532",SR-RJ,DEL5/4,UOP02/RJ
3,99981.0,2018-01-01,segunda-feira,01:15:00,RS,386.0,134,SARANDI,Ingestão de Álcool,Colisão transversal,...,0,2,0,0,2,"-27,953636","-52,916374",SR-RS,DEL9/14,UOP01/RS
4,99982.0,2018-01-01,segunda-feira,00:20:00,RS,293.0,"151,7",CANDIOTA,Falta de Atenção à Condução,Saída de leito carroçável,...,1,0,0,1,1,"-31,395214","-53,78391174",SR-RS,DEL9/11,UOP03/RS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69290,252256.0,2018-12-24,segunda-feira,09:15:00,PI,343.0,"263,1",CAMPO MAIOR,Agressão Externa,Colisão com objeto estático,...,0,1,0,0,1,"-4,819326","-42,158821",SR-PI,DEL17/1,UOP03/PI
69291,252652.0,2018-12-12,quarta-feira,07:00:00,BA,101.0,321,PRESIDENTE TANCREDO NEVES,Falta de Atenção à Condução,Saída de leito carroçável,...,0,0,0,1,1,"-13,44768518","-39,42066193",SR-BA,DEL10/5,UOP03/BA
69292,252801.0,2018-11-15,quinta-feira,10:48:00,SP,116.0,529,BARRA DO TURVO,Falta de Atenção à Condução,Colisão traseira,...,0,0,1,1,2,"-24,939211","-48,301248",SR-SP,DEL6/5,UOP03/SP
69293,253040.0,2018-11-23,sexta-feira,19:30:00,RS,472.0,"573,5",URUGUAIANA,Desobediência às normas de trânsito pelo condutor,Queda de ocupante de veículo,...,1,1,0,1,2,"-29,76355779","-57,05200195",SR-RS,DEL9/13,UOP01/RS
69294,253078.0,2018-10-01,segunda-feira,04:31:00,GO,40.0,9,LUZIANIA,Não guardar distância de segurança,Saída de leito carroçável,...,0,0,0,1,1,"-16,131158","-47,957739",SR-DF,UOP01/DF,NaN

In [3]:
#vizualizando segundo dataframe
df_2019

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,182210.0,2019-01-01,terça-feira,01:30:00,SP,116.0,218,GUARULHOS,Falta de Atenção à Condução,Colisão com objeto estático,...,0,0,0,4,1,"-23,46052014","-46,48772478",SR-SP,DEL6/1,UOP01/SP
1,182211.0,2019-01-01,terça-feira,01:30:00,PR,373.0,"177,3",PONTA GROSSA,Falta de Atenção à Condução,Colisão traseira,...,0,0,0,1,1,"-25,05533957","-50,22776753",SR-PR,DEL7/3,UOP01/PR
2,182212.0,2019-01-01,terça-feira,00:45:00,SC,101.0,16,GARUVA,Animais na Pista,Colisão com objeto estático,...,0,0,0,1,1,"-26,1216","-48,8826",SR-SC,DEL8/3,UOP01/SC
3,182214.0,2019-01-01,terça-feira,00:00:00,CE,20.0,"429,5",FORTALEZA,Ingestão de Substâncias Psicoativas,Colisão com objeto estático,...,1,0,0,1,1,"-3,76999","-38,670063",SR-CE,DEL16/1,UOP02/CE
4,182215.0,2019-01-01,terça-feira,01:00:00,MG,381.0,327,NOVA ERA,Falta de Atenção à Condução,Colisão transversal,...,1,1,0,1,2,"-19,7609","-43,0306",SR-MG,DEL4/3,UOP01/MG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67441,266255.0,2019-10-07,segunda-feira,09:10:00,ES,101.0,"270,5",SERRA,Falta de Atenção à Condução,Tombamento,...,1,1,0,1,2,"-20,23107","-40,27387",SR-ES,DEL12/2,UOP01/ES
67442,266406.0,2019-11-25,segunda-feira,07:20:00,PR,116.0,125,FAZENDA RIO GRANDE,Falta de Atenção à Condução,Colisão lateral,...,0,1,1,1,2,"-25,59505","-49,31631",SR-PR,DEL7/1,UOP03/PR
67443,266434.0,2019-06-03,segunda-feira,19:00:00,CE,222.0,"1,4",CAUCAIA,Não guardar distância de segurança,Colisão traseira,...,1,1,0,1,2,"-3,736507","-38,65337",SR-CE,DEL16/1,UOP01/CE
67444,266573.0,2019-07-13,sábado,19:35:00,PR,373.0,425,CANDOI,Defeito Mecânico no Veículo,Saída de leito carroçável,...,1,0,0,1,1,"-25,7118","-52,18374",SR-PR,DEL7/3,UOP02/PR
67445,266627.0,2019-10-22,terça-feira,20:20:00,BA,324.0,608,SIMOES FILHO,Defeito na Via,Queda de ocupante de veículo,...,0,0,0,1,1,"-12,78156","-38,41656",SR-BA,DEL10/1,UOP01/BA

In [4]:
#vizualizando terceiro dataframe
df_2020

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,260031.0,2020-01-01,quarta-feira,01:00:00,TO,153.0,"678,1",GURUPI,Animais na Pista,Atropelamento de Animal,...,5,0,0,5,1,"-11,77460203","-49,10744996",SR-TO,UOP01/TO,NaN
1,260036.0,2020-01-01,quarta-feira,01:00:00,RJ,116.0,178,NOVA IGUACU,Falta de Atenção do Pedestre,Atropelamento de Pedestre,...,0,1,0,0,1,"-22,75223028","-43,4379103",SR-RJ,DEL5/1,UOP02/RJ
2,260037.0,2020-01-01,quarta-feira,01:52:00,SC,101.0,"206,9",SAO JOSE,Ingestão de Álcool,Colisão lateral,...,0,1,0,1,2,"-27,59193546","-48,61824557",SR-SC,DEL8/1,UOP01/SC
3,260038.0,2020-01-01,quarta-feira,01:15:00,RO,364.0,236,CACOAL,Velocidade Incompatível,Saída de leito carroçável,...,1,0,0,1,1,"-11,44624577","-61,43761218",SR-RO,DEL21/2,UOP02/RO
4,260039.0,2020-01-01,quarta-feira,01:30:00,PR,153.0,360,REBOUCAS,Ingestão de Álcool,Capotamento,...,4,0,0,6,1,"-25,67503796","-50,75089805",SR-PR,DEL7/3,UOP04/PR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63543,364615.0,2020-03-20,sexta-feira,09:00:00,RN,304.0,"171,8",ANGICOS,Falta de Atenção à Condução,Colisão traseira,...,1,2,0,2,4,"-5,68711053","-36,419458",SR-RN,UOP03,DEL01
63544,364810.0,2020-09-12,sábado,23:50:00,BA,116.0,"11,5",VITORIA DA CONQUISTA,Ingestão de Álcool,Colisão lateral,...,0,2,0,1,2,"-14,87308214","-40,87141514",SR-BA,UOP01,DEL08
63545,364817.0,2020-10-30,sexta-feira,10:30:00,BA,116.0,"14,3",VITORIA DA CONQUISTA,Falta de Atenção à Condução,Colisão lateral,...,0,2,0,2,2,"-14,89597653","-40,86098671",SR-BA,UOP01,DEL08
63546,364835.0,2020-09-20,domingo,23:00:00,BA,116.0,8,VITORIA DA CONQUISTA,Velocidade Incompatível,Queda de ocupante de veículo,...,0,0,0,1,1,"-14,84732305","-40,88634968",SR-BA,UOP01,DEL08
63547,364903.0,2020-10-31,sábado,02:10:00,BA,116.0,3,VITORIA DA CONQUISTA,Animais na Pista,Atropelamento de Animal,...,1,0,0,1,1,"-14,824848","-40,861311",SR-BA,UOP01,DEL08

In [5]:
#vizualizando terceiro dataframe
df_2021

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,331693.0,2021-01-01,sexta-feira,00:02:00,SC,101.0,"314,9",LAGUNA,Ingestão de álcool pelo condutor,Colisão traseira,...,0,2,0,1,2,-28.430294,-48.849251,SR-SC,UOP01,DEL02
1,331694.0,2021-01-01,sexta-feira,00:15:00,PR,376.0,188,MARIALVA,Velocidade Incompatível,Colisão com objeto,...,0,0,0,2,1,-23.466349,-51.828080,SR-PR,UOP01,DEL09
2,331696.0,2021-01-01,sexta-feira,00:00:00,SP,116.0,"110,6",TAUBATE,Demais falhas mecânicas ou elétricas,Incêndio,...,0,1,0,0,1,-23.034126,-45.552700,SR-SP,UOP01,DEL06
3,331699.0,2021-01-01,sexta-feira,01:20:00,SC,101.0,111,NAVEGANTES,Manobra de mudança de faixa,Colisão lateral,...,0,1,0,2,2,-26.839557,-48.714181,SR-SC,UOP04,DEL04
4,331701.0,2021-01-01,sexta-feira,00:30:00,PE,101.0,"45,1",IGARASSU,Reação tardia ou ineficiente do condutor,Colisão traseira,...,1,1,0,1,2,-7.865213,-34.907152,SR-PE,UOP02,DEL01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64510,425426.0,2021-05-13,quinta-feira,03:15:00,MG,381.0,"775,3",CAMPANHA,Condutor deixou de manter distância do veículo...,Colisão traseira,...,0,2,0,2,2,-21.790183,-45.446659,SR-MG,UOP02,DEL16
64511,425436.0,2021-11-15,segunda-feira,23:00:00,PA,10.0,"248,4",AURORA DO PARA,Transitar na contramão,Colisão transversal,...,1,1,0,2,2,-2.267754,-47.563084,SR-PA,UOP01,DEL02
64512,428107.0,2021-09-21,terça-feira,01:10:00,MG,50.0,20,ARAGUARI,Condutor Dormindo,Colisão com objeto,...,2,1,0,7,1,-18.587210,-48.056456,SR-MG,UOP02,DEL15
64513,435016.0,2021-12-29,quarta-feira,13:40:00,AC,364.0,170,BUJARI,Pista esburacada,Queda de ocupante de veículo,...,1,0,0,1,1,-9.766854,-68.056811,SR-AC,UOP01,DEL01
64514,441173.0,2021-08-22,domingo,17:10:00,MT,364.0,498,JANGADA,Reação tardia ou ineficiente do condutor,Colisão traseira,...,0,1,0,1,2,-15.263832,-56.455487,SR-MT,UOP02,DEL01

<div class="alert alert-block alert-info">
    2° Tarefa
<div>

<div class="alert alert-block alert-info" style="background-color:#b9ceac; color:#000; border-radius:15px;" >
    a)
<div>

Olhando o numero de index podemos ver quantas variaveis o dataframe armazena

Numero de acidentes em 2018

In [6]:
len(df_2018.index)

69295

Numero de acidentes em 2019

In [7]:
len(df_2019.index)

67446

Numero de acidentes em 2020

In [8]:
len(df_2020.index)

63548

Numero de acidentes em 2021

In [9]:
len(df_2021.index)

64515

<div class="alert alert-block alert-info" style="background-color:#b9ceac; color:#000; border-radius:15px;">
    b)
<div>

Olhando o numero de colunas podemos ver quantas variaveis o dataframe armazena.

In [10]:
len(df_2018.columns)

30

In [11]:
len(df_2019.columns)

30

In [12]:
len(df_2020.columns)

30

In [13]:
len(df_2021.columns)

30

Podemos ver que todos os datafames armazenam 30 variaveis.

<div class="alert alert-block alert-info" style="background-color:#b9ceac; color:#000; border-radius:15px;">
    c)
<div>

Para saber o numero de acidentes totais, precisamos criar um novo dataframe que junte todos os dados.

In [14]:
df_total = pd.concat([df_2018,df_2019,df_2020,df_2021])

In [15]:
#vizualizando o dataframe total
df_total

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,99973.0,2018-01-01,segunda-feira,00:20:00,RJ,116.0,"303,5",RESENDE,Condutor Dormindo,Saída de leito carroçável,...,4,1,0,4,1,"-22,46937","-44,44705",SR-RJ,DEL5/7,UOP03/RJ
1,99976.0,2018-01-01,segunda-feira,00:40:00,SC,282.0,"0,4",FLORIANOPOLIS,Não guardar distância de segurança,Colisão traseira,...,2,1,0,2,2,"-27,59971687","-48,57565694",SR-SC,DEL8/1,UOP01/SC
2,99977.0,2018-01-01,segunda-feira,00:30:00,RJ,493.0,1,ITABORAI,Ultrapassagem Indevida,Colisão frontal,...,0,3,1,1,3,"-22,763901","-42,927532",SR-RJ,DEL5/4,UOP02/RJ
3,99981.0,2018-01-01,segunda-feira,01:15:00,RS,386.0,134,SARANDI,Ingestão de Álcool,Colisão transversal,...,0,2,0,0,2,"-27,953636","-52,916374",SR-RS,DEL9/14,UOP01/RS
4,99982.0,2018-01-01,segunda-feira,00:20:00,RS,293.0,"151,7",CANDIOTA,Falta de Atenção à Condução,Saída de leito carroçável,...,1,0,0,1,1,"-31,395214","-53,78391174",SR-RS,DEL9/11,UOP03/RS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64510,425426.0,2021-05-13,quinta-feira,03:15:00,MG,381.0,"775,3",CAMPANHA,Condutor deixou de manter distância do veículo...,Colisão traseira,...,0,2,0,2,2,-21.790183,-45.446659,SR-MG,UOP02,DEL16
64511,425436.0,2021-11-15,segunda-feira,23:00:00,PA,10.0,"248,4",AURORA DO PARA,Transitar na contramão,Colisão transversal,...,1,1,0,2,2,-2.267754,-47.563084,SR-PA,UOP01,DEL02
64512,428107.0,2021-09-21,terça-feira,01:10:00,MG,50.0,20,ARAGUARI,Condutor Dormindo,Colisão com objeto,...,2,1,0,7,1,-18.58721,-48.056456,SR-MG,UOP02,DEL15
64513,435016.0,2021-12-29,quarta-feira,13:40:00,AC,364.0,170,BUJARI,Pista esburacada,Queda de ocupante de veículo,...,1,0,0,1,1,-9.766854,-68.056811,SR-AC,UOP01,DEL01
64514,441173.0,2021-08-22,domingo,17:10:00,MT,364.0,498,JANGADA,Reação tardia ou ineficiente do condutor,Colisão traseira,...,0,1,0,1,2,-15.263832,-56.455487,SR-MT,UOP02,DEL01

Neste momento eu separo o dataframe por municipio através da função `grupby()`, que indexa o dataframe através do nome do municipio, e com uma ação conjunta da função `count()`, conta o numero de ocorrencias validas (não conta NaN), atribuindo esse numero a todas as colunas.

In [16]:
df_total.groupby(['municipio']).count()

,id,data_inversa,dia_semana,horario,uf,br,km,causa_acidente,tipo_acidente,classificacao_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
municipio,,,,,,,,,,,,,,,,,,,,,
ABADIA DE GOIAS,145,145,145,145,145,145,145,145,145,145,...,145,145,145,145,145,145,145,145,145,145
ABADIANIA,253,253,253,253,253,253,253,253,253,253,...,253,253,253,253,253,253,253,253,253,253
ABARE,26,26,26,26,26,26,26,26,26,26,...,26,26,26,26,26,26,26,26,26,26
ABEL FIGUEIREDO,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
ABRE CAMPO,76,76,76,76,76,74,74,76,76,76,...,76,76,76,76,76,76,76,76,76,76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XAPURI,25,25,25,25,25,25,25,25,25,25,...,25,25,25,25,25,25,25,25,25,11
XAXIM,197,197,197,197,197,197,197,197,197,197,...,197,197,197,197,197,197,197,197,197,197
XEXEU,38,38,38,38,38,38,38,38,38,38,...,38,38,38,38,38,38,38,38,38,38
XINGUARA,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
ZE DOCA,21,21,21,21,21,21,21,21,21,21,...,21,21,21,21,21,21,21,21,21,21

Como basta saber apenas uma vez qual o valor que queremos, limitei a uma coluna por meio do `.iloc()`, e por meio da função `sort_values()` organizei em ordem decrescente, de forma que os municipios com mais acidentes apareçam no topo. Ademais, limitei o numero de linhas para 5, de forma que só vamos ver os 5 primeiros municipios. E por fim, troquei o nome da primeira coluna que era `id` por `numero de acidentes`.

In [17]:
df_total.groupby(['municipio']).count().sort_values('id', ascending=False).iloc[:5,:1].rename(columns = {'id':'numero de acidentes'})

           numero de acidentes
municipio
BRASILIA                  3978
CURITIBA                  3962
SAO JOSE                  3011
GUARULHOS                 2781
PALHOCA                   2496

<div class="alert alert-block alert-info" style="background-color:#b9ceac; color:#000; border-radius:15px;">
    d)
<div>

Primeiramente vamos separar apenas os acidentes que aconteceram na Paraiba.

In [18]:
paraiba = df_total[(df_total.uf == "PB")]
#vizualizando
paraiba

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
11,99991.0,2018-01-01,segunda-feira,02:00:00,PB,230.0,4,CABEDELO,Velocidade Incompatível,Colisão traseira,...,2,3,0,3,2,"-7,0064375","-34,82958913",SR-PB,DEL14/1,UOP00/PB
52,100035.0,2018-01-01,segunda-feira,06:00:00,PB,230.0,"26,9",JOAO PESSOA,Falta de Atenção à Condução,Tombamento,...,0,0,0,1,1,"-7,235786","-34,9252969",SR-PB,DEL14/1,UOP00/PB
75,100062.0,2018-01-01,segunda-feira,12:25:00,PB,101.0,"50,9",RIO TINTO,Falta de Atenção à Condução,Saída de leito carroçável,...,0,0,0,1,1,"-6,92936","-35,1042886",SR-PB,DEL14/1,UOP03/PB
144,100141.0,2018-01-01,segunda-feira,17:35:00,PB,230.0,28,JOAO PESSOA,Falta de Atenção à Condução,Colisão traseira,...,0,2,0,1,2,"-7,1651","-34,8941",SR-PB,DEL14/1,UOP00/PB
186,100192.0,2018-01-01,segunda-feira,21:20:00,PB,230.0,"217,1",SOLEDADE,Falta de Atenção do Pedestre,Atropelamento de Pedestre,...,1,0,1,1,1,"-7,05279996","-36,3760201",SR-PB,DEL14/2,UOP02/PB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64210,412742.0,2021-11-27,sábado,18:45:00,PB,101.0,"82,3",BAYEUX,Ingestão de álcool ou de substâncias psicoativ...,Atropelamento de Pedestre,...,1,0,0,2,1,-7.129836,-34.935653,SR-PB,UOP01,DEL01
64237,413490.0,2021-07-17,sábado,09:20:00,PB,101.0,115,CAAPORA,Acumulo de água sobre o pavimento,Saída de leito carroçável,...,1,1,0,2,1,-7.396321,-34.955777,SR-PB,UOP02,DEL01
64310,415224.0,2021-12-30,quinta-feira,08:40:00,PB,230.0,"17,5",JOAO PESSOA,Pista Escorregadia,Tombamento,...,1,0,0,1,1,-7.1121,-34.8426,SR-PB,UOP01,DEL01
64487,424111.0,2021-12-26,domingo,05:30:00,PB,230.0,"447,1",APARECIDA,Ausência de reação do condutor,Saída de leito carroçável,...,1,0,0,2,1,-6.786,-38.085,SR-PB,UOP03,DEL03
64497,424754.0,2021-07-03,sábado,19:30:00,PB,361.0,5,PATOS,Condutor deixou de manter distância do veículo...,Colisão traseira,...,1,0,1,1,2,-7.034298,-37.302327,SR-PB,UOP01,DEL03

Agora, selecionamos a coluna que conta o numero de feridos graves e contamos as que possui pelo menos um ferido.

In [19]:
print('Numero de acidentes graves na Paraíba: ', paraiba[paraiba.feridos_graves > 0].feridos_graves.count())

Numero de acidentes graves na Paraíba:  1516

<div class="alert alert-block alert-info">
    3° Tarefa
<div>

<div class="alert alert-block alert-info" style="background-color:#b9ceac; color:#000; border-radius:15px;">
    a)
<div>

In [20]:
#separando dataframes por meio da função groupby, agrupando por unidade federativas,
#e contando o numero de acidentes de cada dia da semana.
uf_18 = df_2018.groupby(['uf']).count().sort_values('id').iloc[:,:1].rename(columns = {"id":"numero de acidentes"})
uf_19 = df_2019.groupby(['uf']).count().sort_values('id').iloc[:,:1].rename(columns = {"id":"numero de acidentes"})
uf_20 = df_2020.groupby(['uf']).count().sort_values('id').iloc[:,:1].rename(columns = {"id":"numero de acidentes"})
uf_21 = df_2021.groupby(['uf']).count().sort_values('id').iloc[:,:1].rename(columns = {"id":"numero de acidentes"})

#juntando dataframes em um só
uf_total = pd.concat([uf_18,uf_19,uf_20,uf_21], keys = ['2018','2019','2020','2021'])

#criando arquivo csv
uf_total.to_csv("Acidentes_Por_UF_[18,19,20,21].csv")

#vizualizando dataframe
uf_total

         numero de acidentes
     uf
2018 AM                  124
     AP                  173
     AC                  235
     RR                  236
     SE                  559
...                      ...
2021 RS                 4538
     RJ                 4565
     PR                 7335
     SC                 7889
     MG                 8323

[108 rows x 1 columns]

<div class="alert alert-block alert-info" style="background-color:#b9ceac; color:#000; border-radius:15px;">
    b)
<div>

In [21]:
#ordem dos dias da semana em forma de lista
ordem_ds = ["segunda-feira","terça-feira","quarta-feira","quinta-feira","sexta-feira",'sábado','domingo']
#separando pelo grupo dia da semana e contando quantos acidentes cada dia teve

ds_18 = df_2018.groupby(['dia_semana']).count().iloc[:,:1].rename(columns = {"id":"nº acidentes"})
ds_19 = df_2019.groupby(['dia_semana']).count().iloc[:,:1].rename(columns = {"id":"nº acidentes"})
ds_20 = df_2020.groupby(['dia_semana']).count().iloc[:,:1].rename(columns = {"id":"nº acidentes"})
ds_21 = df_2021.groupby(['dia_semana']).count().iloc[:,:1].rename(columns = {"id":"nº acidentes"})

#ordenando os dataframes com base na lista que mostra a ordem correta dos dias da semana

ds_18.index = pd.Categorical(ds_18.index,ordem_ds,ordered=True)
ds_18.sort_index(inplace=True)

ds_19.index = pd.Categorical(ds_19.index,ordem_ds,ordered=True)
ds_19.sort_index(inplace=True)

ds_20.index = pd.Categorical(ds_20.index,ordem_ds,ordered=True)
ds_20.sort_index(inplace=True)

ds_21.index = pd.Categorical(ds_19.index,ordem_ds,ordered=True)
ds_21.sort_index(inplace=True)

#juntando dataframes em um só
ds_total = pd.concat([ds_18,ds_19,ds_20,ds_21], keys = ['2018','2019','2020','2021'])

#criando arquivo csv
ds_total.to_csv("Acidentes_Por_DS_[18,19,20,21].csv")

#vizualizando dataframe
ds_total

                    nº acidentes
2018 segunda-feira          9422
     terça-feira            8665
     quarta-feira           8824
     quinta-feira           9230
     sexta-feira           10632
     sábado                11239
     domingo               11283
2019 segunda-feira          9134
     terça-feira            8405
     quarta-feira           8374
     quinta-feira           8755
     sexta-feira           10381
     sábado                11099
     domingo               11298
2020 segunda-feira          8519
     terça-feira            7779
     quarta-feira           8155
     quinta-feira           8244
     sexta-feira            9764
     sábado                10667
     domingo               10420
2021 segunda-feira         10815
     terça-feira            7994
     quarta-feira           8242
     quinta-feira           8637
     sexta-feira           10168
     sábado                10867
     domingo                7792

<div class="alert alert-block alert-info">
    4° Tarefa
<div>

<div class="alert alert-block alert-info" style="background-color:#b9ceac; color:#000; border-radius:15px;">
    a)
<div>

Primeiramente precisamos calcular um ranking do numero de acidentes variando de acordo com os anos, para isso irei agrupar o dataframe pela coluna `causa_acidente` por meio da função `groupby()`, que ira fazer um split do dataframe, e em conjunto com a função `count()` ira contar quantas vezes a causa do acidente aparece.

## Para o ano de 2018

In [22]:
#dataframe completo
df_2018.groupby(['causa_acidente']).count().iloc[:,:1].rename(columns = {'id':'n° acidentes'}).sort_values(by='n° acidentes', ascending=False)

                                                    n° acidentes
causa_acidente
Falta de Atenção à Condução                                25830
Desobediência às normas de trânsito pelo condutor           7189
Velocidade Incompatível                                     6849
Ingestão de Álcool                                          5201
Não guardar distância de segurança                          4262
Defeito Mecânico no Veículo                                 3716
Condutor Dormindo                                           2633
Pista Escorregadia                                          2549
Falta de Atenção do Pedestre                                2073
Animais na Pista                                            1614
Ultrapassagem Indevida                                      1333
Defeito na Via                                              1126
Avarias e/ou desgaste excessivo no pneu                     1011
Mal Súbito                                                   677
Restrição de Visibilidade                                    539
Objeto estático sobre o leito carroçável                     539
Carga excessiva e/ou mal acondicionada                       367
Agressão Externa                                             356
Fenômenos da Natureza                                        310
Ingestão de álcool e/ou substâncias psicoativas...           297
Sinalização da via insuficiente ou inadequada                292
Desobediência às normas de trânsito pelo pedestre            273
Deficiência ou não Acionamento do Sistema de Il...           186
Ingestão de Substâncias Psicoativas                           73

In [23]:
print('Causa mais frequente:')
df_2018.groupby(['causa_acidente']).count().rename(columns = {'id':'n° acidentes'}).sort_values(by='n° acidentes', ascending=False).iloc[:1,:1]

Causa mais frequente:

                             n° acidentes
causa_acidente
Falta de Atenção à Condução         25830

In [24]:
print('Causa mais rara:')
df_2018.groupby(['causa_acidente']).count().rename(columns = {'id':'n° acidentes'}).sort_values(by='n° acidentes', ascending=False).iloc[-1:,:1]

Causa mais rara:

                                     n° acidentes
causa_acidente
Ingestão de Substâncias Psicoativas            73

## Para o ano de 2019

In [25]:
#dataframe completo
df_2019.groupby(['causa_acidente']).count().iloc[:,:1].rename(columns = {'id':'n° acidentes'}).sort_values(by='n° acidentes', ascending=False)

                                                    n° acidentes
causa_acidente
Falta de Atenção à Condução                                24992
Desobediência às normas de trânsito pelo condutor           8098
Velocidade Incompatível                                     6028
Ingestão de Álcool                                          5419
Não guardar distância de segurança                          4214
Defeito Mecânico no Veículo                                 3732
Condutor Dormindo                                           2483
Pista Escorregadia                                          2186
Falta de Atenção do Pedestre                                1971
Animais na Pista                                            1527
Ultrapassagem Indevida                                      1173
Defeito na Via                                               973
Avarias e/ou desgaste excessivo no pneu                      799
Mal Súbito                                                   715
Restrição de Visibilidade                                    493
Objeto estático sobre o leito carroçável                     437
Ingestão de álcool e/ou substâncias psicoativas...           394
Desobediência às normas de trânsito pelo pedestre            392
Agressão Externa                                             384
Carga excessiva e/ou mal acondicionada                       305
Sinalização da via insuficiente ou inadequada                247
Fenômenos da Natureza                                        230
Deficiência ou não Acionamento do Sistema de Il...           160
Ingestão de Substâncias Psicoativas                           94

In [26]:
print('Causa mais frequente:')
df_2019.groupby(['causa_acidente']).count().rename(columns = {'id':'n° acidentes'}).sort_values(by='n° acidentes', ascending=False).iloc[:1,:1]

Causa mais frequente:

                             n° acidentes
causa_acidente
Falta de Atenção à Condução         24992

In [27]:
print('Causa mais rara:')
df_2019.groupby(['causa_acidente']).count().rename(columns = {'id':'n° acidentes'}).sort_values(by='n° acidentes', ascending=False).iloc[-1:,:1]

Causa mais rara:

                                     n° acidentes
causa_acidente
Ingestão de Substâncias Psicoativas            94

## Para o ano de 2020

In [28]:
#dataframe completo
df_2020.groupby(['causa_acidente']).count().iloc[:,:1].rename(columns = {'id':'n° acidentes'}).sort_values(by='n° acidentes', ascending=False)

                                                    n° acidentes
causa_acidente
Falta de Atenção à Condução                                22409
Desobediência às normas de trânsito pelo condutor           8802
Velocidade Incompatível                                     5886
Ingestão de Álcool                                          5069
Defeito Mecânico no Veículo                                 3742
Não guardar distância de segurança                          3606
Condutor Dormindo                                           2109
Pista Escorregadia                                          2017
Falta de Atenção do Pedestre                                1641
Animais na Pista                                            1410
Ultrapassagem Indevida                                      1084
Defeito na Via                                               960
Avarias e/ou desgaste excessivo no pneu                      902
Mal Súbito                                                   584
Restrição de Visibilidade                                    483
Objeto estático sobre o leito carroçável                     446
Desobediência às normas de trânsito pelo pedestre            388
Carga excessiva e/ou mal acondicionada                       377
Ingestão de álcool e/ou substâncias psicoativas...           357
Agressão Externa                                             342
Sinalização da via insuficiente ou inadequada                241
Fenômenos da Natureza                                        221
Deficiência ou não Acionamento do Sistema de Il...           187
Ingestão de Substâncias Psicoativas                           86
Reação tardia ou ineficiente do condutor                      24
Condutor deixou de manter distância do veículo ...            21
Ausência de reação do condutor                                21
Manobra de mudança de faixa                                   19
Transitar na contramão                                        14
Acessar a via sem observar a presença dos outro...            13
Demais falhas mecânicas ou elétricas                          13
Desrespeitar a preferência no cruzamento                       8
Ingestão de álcool pelo condutor                               8
Chuva                                                          6
Conversão proibida                                             6
Trafegar com motocicleta (ou similar) entre as ...             5
Pedestre andava na pista                                       4
Condutor desrespeitou a iluminação vermelha do ...             4
Acesso irregular                                               3
Transitar no acostamento                                       3
Falta de acostamento                                           3
Afundamento ou ondulação no pavimento                          2
Demais falhas na via                                           2
Iluminação deficiente                                          2
Mal súbito do condutor                                         2
Entrada inopinada do pedestre                                  2
Acumulo de água sobre o pavimento                              2
Acumulo de areia ou detritos sobre o pavimento                 1
Acostamento em desnível                                        1
Acumulo de óleo sobre o pavimento                              1
Condutor usando celular                                        1
Pista esburacada                                               1
Ausência de sinalização                                        1
Pedestre cruzava a pista fora da faixa                         1
Ingestão de álcool ou de substâncias psicoativa...             1
Curva acentuada                                                1
Fumaça                                                         1
Frear bruscamente                                              1
Estacionar ou parar em local proibido                          1

In [29]:
print('Causa mais frequente:')
df_2020.groupby(['causa_acidente']).count().rename(columns = {'id':'n° acidentes'}).sort_values(by='n° acidentes', ascending=False).iloc[:1,:1]

Causa mais frequente:

                             n° acidentes
causa_acidente
Falta de Atenção à Condução         22409

In [30]:
print('Causa mais rara:')
df_2020.groupby(['causa_acidente']).count().rename(columns = {'id':'n° acidentes'}).sort_values(by='n° acidentes', ascending=False).iloc[-1:,:1]

Causa mais rara:

                                       n° acidentes
causa_acidente
Estacionar ou parar em local proibido             1

## Para o ano de 2021

In [31]:
#dataframe completo
df_2021.groupby(['causa_acidente']).count().iloc[:,:1].rename(columns = {'id':'n° acidentes'}).sort_values(by='n° acidentes', ascending=False)

                                                    n° acidentes
causa_acidente
Reação tardia ou ineficiente do condutor                    6903
Velocidade Incompatível                                     6742
Ausência de reação do condutor                              5601
Acessar a via sem observar a presença dos outro...          5194
Condutor deixou de manter distância do veículo ...          5117
...                                                          ...
Semáforo com defeito                                           8
Modificação proibida                                           8
Participar de racha                                            7
Sistema de drenagem ineficiente                                3
Sinalização encoberta                                          3

[71 rows x 1 columns]

In [32]:
print('Causa mais frequente:')
df_2021.groupby(['causa_acidente']).count().rename(columns = {'id':'n° acidentes'}).sort_values(by='n° acidentes', ascending=False).iloc[:1,:1]

Causa mais frequente:

                                          n° acidentes
causa_acidente
Reação tardia ou ineficiente do condutor          6903

In [33]:
print('Causa mais rara:')
df_2021.groupby(['causa_acidente']).count().rename(columns = {'id':'n° acidentes'}).sort_values(by='n° acidentes', ascending=False).iloc[-1:,:1]

Causa mais rara:

                       n° acidentes
causa_acidente
Sinalização encoberta             3

## Para todos os anos

In [34]:
#dataframe completo
df_total.groupby(['causa_acidente']).count().iloc[:,:1].rename(columns = {'id':'n° acidentes'}).sort_values(by='n° acidentes', ascending=False)

                                                   n° acidentes
causa_acidente
Falta de Atenção à Condução                               73231
Velocidade Incompatível                                   25505
Desobediência às normas de trânsito pelo condutor         24089
Ingestão de Álcool                                        15689
Não guardar distância de segurança                        12082
...                                                         ...
Semáforo com defeito                                          8
Modificação proibida                                          8
Participar de racha                                           7
Sistema de drenagem ineficiente                               3
Sinalização encoberta                                         3

[86 rows x 1 columns]

In [35]:
print('Causa mais frequente:')
df_total.groupby(['causa_acidente']).count().rename(columns = {'id':'n° acidentes'}).sort_values(by='n° acidentes', ascending=False).iloc[:1,:1]

Causa mais frequente:

                             n° acidentes
causa_acidente
Falta de Atenção à Condução         73231

In [36]:
print('Causa mais rara:')
df_total.groupby(['causa_acidente']).count().rename(columns = {'id':'n° acidentes'}).sort_values(by='n° acidentes', ascending=False).iloc[-1:,:1]

Causa mais rara:

                       n° acidentes
causa_acidente
Sinalização encoberta             3

<div class="alert alert-block alert-info" style="background-color:#b9ceac; color:#000; border-radius:15px;">
    b)
<div>

Para usar apenas o mês precisamos tratar a coluna `data_inversa`. Para isso irei importar a lib `datetime`, da qual a lib `pandas` pode utilizar de alguns artificios para esse tratamento de dados. Com a função `pd.to_datetime()` eu transformo o objeto que era a coluna `data_inversa` em uma data reconhecido pelo script. Com isso feito posso utilizar a função `dt.month` que identifica o mês desta data.

In [37]:
import datetime

## Para 2018

In [38]:
df_2018['mes'] = pd.to_datetime(df_2018['data_inversa']).dt.month

Para realizar a operação da proporção, pegarei a coluna de `ilesos/feridos_graves` e irei dividir pela coluna `pessoas` (que se refere ao número de pessoas envolvidas no acidente), dessa forma terei o retorno da proporção desejada.

In [39]:
mes_2018 = df_2018.loc[:,['mes','pessoas','ilesos','feridos_graves']]
a = mes_2018.groupby(by='mes').sum()
prop_ilesos = (a['ilesos']/a['pessoas'])
prop_feridos = (a['feridos_graves']/a['pessoas'])
prop = pd.DataFrame(prop_ilesos).rename(columns={0:'proporção ilesos'}).round(4)
prop['proporção feridos graves'] = pd.DataFrame(prop_feridos).round(4)
prop

     proporção ilesos  proporção feridos graves
mes
1              0.5133                    0.0906
2              0.4983                    0.0922
3              0.4815                    0.1019
4              0.4302                    0.1128
5              0.4222                    0.1145
6              0.4251                    0.1164
7              0.4375                    0.1103
8              0.4271                    0.1064
9              0.4207                    0.1155
10             0.4302                    0.1126
11             0.4334                    0.1154
12             0.4329                    0.1081

## Para 2019

In [40]:
df_2019['mes'] = pd.to_datetime(df_2019['data_inversa']).dt.month

In [41]:
mes_2019 = df_2019.loc[:,['mes','pessoas','ilesos','feridos_graves']]
a = mes_2019.groupby(by='mes').sum()
prop_ilesos = (a['ilesos']/a['pessoas'])
prop_feridos = (a['feridos_graves']/a['pessoas'])
prop = pd.DataFrame(prop_ilesos).rename(columns={0:'proporção ilesos'}).round(4)
prop['proporção feridos graves'] = pd.DataFrame(prop_feridos).round(4)
prop

     proporção ilesos  proporção feridos graves
mes
1              0.4242                    0.1133
2              0.4241                    0.1068
3              0.4332                    0.1146
4              0.4157                    0.1060
5              0.4152                    0.1208
6              0.4238                    0.1216
7              0.4368                    0.1167
8              0.4131                    0.1167
9              0.4211                    0.1107
10             0.4189                    0.1198
11             0.4258                    0.1110
12             0.4223                    0.1144

## Para 2020

In [42]:
df_2020['mes'] = pd.to_datetime(df_2020['data_inversa']).dt.month

In [43]:
mes_2020 = df_2020.loc[:,['mes','pessoas','ilesos','feridos_graves']]
a = mes_2020.groupby(by='mes').sum()
prop_ilesos = (a['ilesos']/a['pessoas'])
prop_feridos = (a['feridos_graves']/a['pessoas'])
prop = pd.DataFrame(prop_ilesos).rename(columns={0:'proporção ilesos'}).round(4)
prop['proporção feridos graves'] = pd.DataFrame(prop_feridos).round(4)
prop

     proporção ilesos  proporção feridos graves
mes
1              0.4156                    0.1075
2              0.4200                    0.1114
3              0.4010                    0.1126
4              0.3763                    0.1179
5              0.4013                    0.1159
6              0.4233                    0.1159
7              0.4243                    0.1086
8              0.4234                    0.1192
9              0.4160                    0.1174
10             0.4110                    0.1197
11             0.4070                    0.1204
12             0.4123                    0.1220

## Para 2021

In [44]:
df_2021['mes'] = pd.to_datetime(df_2021['data_inversa']).dt.month

In [45]:
mes_2021 = df_2021.loc[:,['mes','pessoas','ilesos','feridos_graves']]
a = mes_2021.groupby(by='mes').sum()
prop_ilesos = (a['ilesos']/a['pessoas'])
prop_feridos = (a['feridos_graves']/a['pessoas'])
prop = pd.DataFrame(prop_ilesos).rename(columns={0:'proporção ilesos'}).round(4)
prop['proporção feridos graves'] = pd.DataFrame(prop_feridos).round(4)
prop

     proporção ilesos  proporção feridos graves
mes
1              0.4257                    0.1124
2              0.4135                    0.1157
3              0.4109                    0.1146
4              0.4061                    0.1226
5              0.4158                    0.1250
6              0.4307                    0.1093
7              0.4319                    0.1134
8              0.4212                    0.1193
9              0.4170                    0.1218
10             0.4145                    0.1176
11             0.4268                    0.1209
12             0.4212                    0.1121

## Para Todos os Anos

In [46]:
df_total['mes'] = pd.to_datetime(df_total['data_inversa']).dt.month

In [47]:
mes_total = df_total.loc[:,['mes','pessoas','ilesos','feridos_graves']]
a = mes_total.groupby(by='mes').sum()
prop_ilesos = (a['ilesos']/a['pessoas'])
prop_feridos = (a['feridos_graves']/a['pessoas'])
prop = pd.DataFrame(prop_ilesos).rename(columns={0:'proporção ilesos'}).round(4)
prop['proporção feridos graves'] = pd.DataFrame(prop_feridos).round(4)
prop

     proporção ilesos  proporção feridos graves
mes
1              0.4484                    0.1050
2              0.4413                    0.1059
3              0.4361                    0.1103
4              0.4103                    0.1142
5              0.4141                    0.1193
6              0.4257                    0.1160
7              0.4330                    0.1124
8              0.4211                    0.1154
9              0.4187                    0.1162
10             0.4184                    0.1176
11             0.4231                    0.1168
12             0.4223                    0.1141

<div class="alert alert-block alert-info" style="background-color:#b9ceac; color:#000; border-radius:15px;">
    c)
<div>

In [48]:
#criando um dataframe com os dados da pandemia
df_pandemia = pd.concat([df_2018,df_2019,df_2020,df_2021], keys = ['2018','2019','2020','2021'],names=['ano','index'])
df_pandemia = df_pandemia.reset_index().drop(['index'],axis=1)

#agrupando o dataframe por ano e contando o número de acidentes que aconteceram em cada ano
df_pandemia = df_pandemia.groupby(['ano']).count().iloc[:,:1].rename(columns={'id':'n° acidentes'})

#criando dataframe com os dados de antes da pandemia
before = pd.DataFrame(df_pandemia.iloc[:2,:].sum()).rename(index={'n° acidentes':'antes da pandemia'})

#criando dataframe com os dados de depois da pandemia
after = pd.DataFrame(df_pandemia.iloc[2:,:].sum()).rename(index={'n° acidentes':'durante a pandemia'})

#concatenando os dados de antes e depois da pandemia para comparar
pd.concat([before,after]).rename(columns={0:'n° acidentes'})

                    n° acidentes
antes da pandemia         136741
durante a pandemia        128063

Percebemos que o numero de acidentes diminuiram durante a pandemia.

In [49]:
df_pandemia

      n° acidentes
ano
2018         69295
2019         67446
2020         63548
2021         64515

Olhando friamente para os números, podemos perceber que em 2020, ano mais afetado pela pandemia, tivemos uma queda drastica do numero de acidentes, uma queda de aproximadamente **8,3%** quando comparado com o ano de 2018.

Porém se olharmos para o ano de 2021, onde começamos a ter a aplicação de vacinas e a volta de algumas atividades presenciais, vemos um aumento de **1,5%** quando comparamos com o ano de 2020. Dessa forma podemos ver um crescimento novamente no número de acidentes.